### PR TITLE
Tag focus

### LINKED ISSUE #1385: "add a tag" loses focus on every key press
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

When adding a tag, the input loses focus on every key press.

### PR DESCRIPTION
**Pull request by SaraVieira**
**What kind of change does this PR introduce?**
Fixes loose focus on keydown

**What is the current behavior?**
Removed focus on keypress

**What is the new behavior?**
Works now

closes #1385

### CODE REVIEW

File: packages/app/src/app/components/EditableTags/index.js [hunk 1]
```diff
@@ -58,10 +67,9 @@ export default function(color) {
...
-  return props => (
-    <Fragment>
-      <GlobalStyle />
-      <TagsInput {...props} />
-    </Fragment>
-  );
-}
+export default props => (
+  <Fragment>
+    <GlobalStyle color={props.template.color()} />
```
Comment (CompuIves) [inline packages/app/src/app/components/EditableTags/index.js]: I think you can put this in, with this you don't have to do `hexToRgb` of `color` in the tag.

```suggestion
    <GlobalStyle color={props.template.color} />
```

File: packages/app/src/app/components/EditableTags/index.js [hunk 2]
```diff
@@ -43,7 +52,7 @@ export default function(color) {
     width: 80px;
 
     &:focus {
-      border-color: ${color.clearer(0.3)()};
+      border-color: ${props => hexToRgb(props.color, 0.3)};
```
Comment (CompuIves) [inline packages/app/src/app/components/EditableTags/index.js]: This should work too:

```suggestion
      border-color: ${props => props.color.clearer(0.3)};
```

Because the template color also has a decorated change.

**Comment by SaraVieira** [comment]
That fixed it yes 💯
