### PR TITLE
Fix live undoing

### LINKED ISSUE #699: Lines mixed together during live code.
Hi Ives,

As requested hereby a screenshot of what happens during live coding:
screen shot 2018-04-06 at 16 41 33

In your Twitch feed you were just typing on a new line, in the code sandbox feed, lines were mixed up.

OS: macOS 10.13.3 (17D102)
Browser: Safari 11.0.3 (13604.5.6)

### PR DESCRIPTION
**Pull request by CompuIves**
Fixes #699

### CODE REVIEW

File: packages/app/src/app/components/CodeEditor/Monaco/test.js [hunk 1]
```diff
@@ -0,0 +1,178 @@
+const TextOperation = require('ot').TextOperation;
```
Comment (CompuIves) [inline packages/app/src/app/components/CodeEditor/Monaco/test.js]: @gijsweterings This is my 'unit test' 😅
