### PR TITLE
Disable fork button while forking

### LINKED ISSUE #844: Fork button doesn't show feedback while forking
# 🐛 bug report

## Description of the problem
Today at React-Europe, we used CodeSandbox (again) and had to fork a sandbox. However, the wifi was pretty slow and thus the fork was not immediate. Thus, it feels like it wasn't working so I clicked again (many times ^^). Then the sandbox reloaded several times with each time a new fork.

## Suggestion
Display a loader while forking or disable the button.

### PR DESCRIPTION
**Pull request by ValentinH**
Fixes #844.

This is a first improvement:
fork-btn

After this, I'd like to work on a better feedback, maybe a circular loader inside the button. What do you think?

**Checklist**:
- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged 
- [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by lbogdan** [comment]
I think it would also be nice to have a *positive* feedback, like maybe changing the text to "Forking...".

**Comment by ValentinH** [comment]
Totally agreed, I've just updated the PR.

**Comment by SaraVieira** [comment]
Hey!!

I was also just working on this! Bless you!! 

There is also a couple more places we have that button, it would be awesome to have that there too 😁

**Comment by ValentinH** [comment]
@SaraVieira I've just checked and found this place where there is also a fork button:
image

Do you see any other places?

**Comment by SaraVieira** [comment]
Awesome!! 

I'm at home and my laptop is in the car but the code looks great and I will check the UI Tomorrow morning and most likely merge it 😁

Can you add to the contributors table ?

**Comment by ValentinH** [comment]
I'm already in the contributors table 🙂

**Comment by ValentinH** [comment]
What do you guys think about this animation?

animated-fork

**Comment by SaraVieira** [comment]
I really like it! Nice css loading 🎉

File: packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx [hunk 1]
```diff
@@ -64,18 +68,24 @@ const LikeButton = ({
...
     }}
     style={style}
     secondary={secondary}
+    disabled={isForking}
     small
   >
     <>
       <Fork style={{ marginRight: '.5rem' }} />
-      Fork
+      {isForking ? 'Forking' : 'Fork'}
```
Comment (CompuIves) [inline packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx]: I think it would be best to name it "Forking..." with the three dots to indicate an action.

File: packages/app/src/app/pages/Sandbox/Editor/Workspace/items/More/index.tsx [hunk 2]
```diff
@@ -27,15 +27,21 @@ class More extends React.PureComponent<Props> {
...
           {!owned ? (
-            <Button small block onClick={this.forkSandbox}>
-              Fork Sandbox
+            <Button
+              small
+              block
+              disabled={isForkingSandbox}
+              onClick={this.forkSandbox}
+            >
+              {isForkingSandbox ? 'Forking Sandbox' : 'Fork Sandbox'}
```
Comment (CompuIves) [inline packages/app/src/app/pages/Sandbox/Editor/Workspace/items/More/index.tsx]: Same here, adding 3 dots `...` would be nice.

File: packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx (hunk 1 above)
Comment (ValentinH) [reply packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx]: Yes, i was hesitating between both because the dots makes the button really larger while forking. Now you convinced me :)

**Comment by ValentinH** [comment]
I'll keep the animation for a follow-up PR. I'll update following requested changes once I have access to my computer :)

**Comment by lbogdan** [comment]
Also, maybe make the button a bit wider, so that when you change the text to "Forking" it doesn't do that annoying wiggle.

**Comment by ValentinH** [comment]
I think we need to decide between both solutions, because having "Forking..."  will force to have the Fork button pretty large. This will look weird compare to siblings buttons. 
What do you think?

**Comment by ValentinH** [comment]
For the animation, being fancy depends on whether we want to change the button markup or not. In my screenshot, I only used one before pseudo element.

**Comment by CompuIves** [comment]
Just played with it, works really well! Thanks for this contribution @ValentinH!
