### PR TITLE
fix vim mode switch

### LINKED ISSUE #118: When disable Vim mode the code disappears
Hello! When I click `preferences` and select `Vim mode` everything is great, **but when open `preferences` again and disable the Vim mode**, the code _**disappears**_... View:

image

Video: https://youtu.be/KOo8K0i_Uog
I'm using Windows 10 x64bit, Chrome 60

### PR DESCRIPTION
**Pull request by johann-sonntagbauer**
ugly hack to work around eslint dependency which redefines the require instance on window
this breaks the monaco loader.js
the following workaround can be removed after migration to monaco (vim mode) is done

That is the most basic solution I could came up with. Please let me know what you think :)

fixes #118

### CODE REVIEW

File: src/app/utils/codemirror/eslint-lint.js [hunk 1]
```diff
@@ -354,7 +354,15 @@ export function fix(source: string) {
 }
 
 export default (async function initialize() {
-  if (!window.eslint && linter === null) {
+  // ugly hack to work around eslint dependency which redefines the require instance on window
+  // this breaks the monaco loader.js
+  // the following workaround can be removed after migration to monaco (vim mode) is done
+  const origRequire = window.require;
```
Comment (CompuIves) [inline src/app/utils/codemirror/eslint-lint.js]: Out of curiosity, why did you add this line?

**Comment by CompuIves** [comment]
Really great, thanks again! Left one question, after that it's ready to merge.

File: src/app/utils/codemirror/eslint-lint.js (hunk 1 above)
Comment (johann-sonntagbauer) [inline src/app/utils/codemirror/eslint-lint.js]: Thats the hacky part of the change. Because eslint will override the window.require reference. So I store the original reference, load eslint and afterwards restore the original reference.

File: src/app/utils/codemirror/eslint-lint.js [hunk 2]
```diff
@@ -367,6 +375,7 @@ export default (async function initialize() {
   while (!window.eslint) {
     // eslint-disable-next-line
     await delay(100);
+    window.require = origRequire;
```
Comment (johann-sonntagbauer) [inline src/app/utils/codemirror/eslint-lint.js]: damn as I see now the placement is wrong here. I have to move it out of the loop. *shame*

File: src/app/utils/codemirror/eslint-lint.js (hunk 1 above)
Comment (CompuIves) [inline src/app/utils/codemirror/eslint-lint.js]: Good one! Ready to merge 😄

**Comment by CompuIves** [comment]
Thanks!!
